RESOURCES:
   image: my-docker-image:1.0
   partition: batch
   gpu: 1
   cpu: 8
   mem: 64
   duration: 1

CMD: cd LOGDIR/code; PYTHONPATH=LOGDIR/code exec python mnist.py

HPARAMS: [
  {
   RUNX.TAG: 'foo',
   lr: 0.01,
   momentum: [0.5, 0.25],
   logdir: LOGDIR,
  },
  {
   RUNX.TAG: 'bar',
   lr: 0.02,
   momentum: [0.25, 0.12],
   logdir: LOGDIR,
  },
]
   
